# DevClaw workflow configuration
# Modify values to customize. Copy to devclaw/projects/<project>/workflow.yaml for project-specific overrides.

roles:
  developer:
    # maxWorkers: 3  # Maximum concurrent developer workers (default: 1)
    models:
      junior: anthropic/claude-haiku-4-5
      medior: anthropic/claude-sonnet-4-5
      senior: anthropic/claude-opus-4-6
  tester:
    models:
      junior: anthropic/claude-haiku-4-5
      medior: anthropic/claude-sonnet-4-5
      senior: anthropic/claude-opus-4-6
  architect:
    models:
      junior: anthropic/claude-sonnet-4-5
      senior: anthropic/claude-opus-4-6
  reviewer:
    models:
      junior: anthropic/claude-haiku-4-5
      senior: anthropic/claude-sonnet-4-5

workflow:
  initial: planning
  reviewPolicy: human  # Options: human (default), agent, auto
  # human — All PRs need human approval on GitHub/GitLab. Heartbeat auto-merges when approved.
  # agent — Agent reviewer checks every PR before merge.
  # auto  — Junior/medior → agent review, senior → human review.
  # roleExecution: parallel  # Options: parallel (default), sequential
  # parallel   — Different roles can work simultaneously (e.g. developer + tester).
  # sequential — Only one role active at a time.
  states:
    planning:
      type: hold
      label: Planning
      color: "#95a5a6"
      on:
        APPROVE: todo
    toResearch:
      type: queue
      role: architect
      label: To Research
      color: "#0075ca"
      priority: 1
      on:
        PICKUP: researching
    researching:
      type: active
      role: architect
      label: Researching
      color: "#4a90e2"
      on:
        COMPLETE:
          target: done
          actions:
            - closeIssue
        BLOCKED: refining
    todo:
      type: queue
      role: developer
      label: To Do
      color: "#428bca"
      priority: 1
      on:
        PICKUP: doing
    doing:
      type: active
      role: developer
      label: Doing
      color: "#f0ad4e"
      on:
        COMPLETE:
          target: toReview
          actions:
            - detectPr
        BLOCKED: refining
    toReview:
      type: queue
      role: reviewer
      label: To Review
      color: "#7057ff"
      priority: 2
      check: prApproved
      on:
        PICKUP: reviewing
        APPROVED:
          target: done  # change to "toTest" to enable test phase
          actions:
            - mergePr
            - gitPull
            - closeIssue  # remove when using test phase (tester closes)
        MERGE_FAILED: toImprove
        CHANGES_REQUESTED: toImprove
        MERGE_CONFLICT: toImprove
    reviewing:
      type: active
      role: reviewer
      label: Reviewing
      color: "#c5def5"
      on:
        APPROVE:
          target: done  # change to "toTest" to enable test phase
          actions:
            - mergePr
            - gitPull
            - closeIssue  # remove when using test phase (tester closes)
        REJECT: toImprove
        BLOCKED: refining
    # --- Test phase (uncomment to enable) ------------------------------------
    # Adds automated QA after review. To enable:
    #   1. Uncomment toTest and testing below
    #   2. Change APPROVED/APPROVE targets above from "done" to "toTest"
    #   3. Remove closeIssue from APPROVED/APPROVE actions above
    #   4. Add tester prompts: devclaw/prompts/tester.md
    #      (or per-project: devclaw/projects/<name>/prompts/tester.md)
    # toTest:
    #   type: queue
    #   role: tester
    #   label: To Test
    #   color: "#5bc0de"
    #   priority: 2
    #   on:
    #     PICKUP: testing
    # testing:
    #   type: active
    #   role: tester
    #   label: Testing
    #   color: "#9b59b6"
    #   on:
    #     PASS:
    #       target: done
    #       actions:
    #         - closeIssue
    #     FAIL:
    #       target: toImprove
    #       actions:
    #         - reopenIssue
    #     REFINE: refining
    #     BLOCKED: refining
    done:
      type: terminal
      label: Done
      color: "#5cb85c"
    toImprove:
      type: queue
      role: developer
      label: To Improve
      color: "#d9534f"
      priority: 3
      on:
        PICKUP: doing
    refining:
      type: hold
      label: Refining
      color: "#f39c12"
      on:
        APPROVE: todo
